### ISSUE TITLE
Error importing psutl

### ISSUE THREAD

**Issue by nixfreak** [juancarlospaco/psutil-nim#18]
`import psutil`

`.nimble/pkgs/psutil.nim(64,38) Error: type mismatch: got <int> but expected 'cint = int32`

OS is: Osx 10.14 
64 bit 
nim version: 1.4 (stable)

I been using **sysinfo** and would really like to use psutil for grabbing networking stats

Thanks 
-Nixfreak

**Comment by johnscillieri** [comment]
I can take a look in a few weeks, around the holiday. Sorry, I don't have the Mac infrastructure at this point to make it easy to test.

**Comment by bung87** [comment]
fixed in https://github.com/juancarlospaco/psutil-nim/pull/24
